cbeleites/hyperSpec

Makefile, README.md, Vignettes/baseline/Makefile, Vignettes/baseline/baseline.Rnw, Vignettes/chondro/Makefile, Vignettes/fileio/Makefile, Vignettes/flu/Makefile, Vignettes/introduction/introduction.Rnw, Vignettes/laser/Makefile, Vignettes/plotting/plotting.Rnw, hyperSpec/DESCRIPTION, hyperSpec/R/spc.fit.poly.R, hyperSpec/data/Makefile, hyperSpec/inst/doc/Makefile
This merge closes issue #31 
* I did several small changes to Makefiles (mainly removal of `--clean` option)
* I have written building instructions
* I fixed issues with vignettes "baseline" and "plotting" - it was not possible to build them with the newer version of hyperSpec
* I fixed a small issue in `spc.fit.poly.below`
=> Issue makefile 31

hyperSpec/R/guesswavelength.R, hyperSpec/R/initialize.R
Finally, I've run tests.
NOTE:
* Changed output of guesswavelength.R if it could not guess. That's becasue seq_len fails when there is no colnames (`colnames` returns NULL).
* Made as.hyperSpec applieble for data.frames. I think that's fair enough, since data.frames available for `new(...)`.
=> Issue new 6

CONTRIBUTING.md
#112 I started to work on the contributor's guide.
=> CONTRIBUTING.md - contributor's guidelines

Makefile, hyperSpec/vignettes/Makefile-local
=> use git clean for Makefile target clean, remove target superclean.  

hyperSpec/_pkgdown.yml, hyperSpec/vignettes/baseline.Rmd, hyperSpec/vignettes/chondro.Rmd, hyperSpec/vignettes/fileio.Rmd, hyperSpec/vignettes/flu.Rmd, hyperSpec/vignettes/hyperSpec.Rmd, hyperSpec/vignettes/laser.Rmd, hyperSpec/vignettes/plotting.Rmd
@bryanhanson, If this suits your needs, merge this PR. I added cleaning up in a separate chunk in order not to run it unintentionally (as could be the case for `setup` chunks in RStudio).
Related: https://github.com/cbeleites/hyperSpec/commit/759c04189d99afe5c08b71694bc8dfa6187647b7#r40051992
=> Clean up workspace in vignettes

.github/workflows/R-CMD-check.yaml, README.md, hyperSpec/.Rbuildignore, hyperSpec/DESCRIPTION, hyperSpec/codecov.yml
Accept this PR only after #159 is accepted as it is an extension of #159.
=> Feature/131 Enable code coverage checking with Codecov

hyperSpec/codecov.yml
Details in https://github.com/cbeleites/hyperSpec/issues/194#issuecomment-655826772
=> Address codecov paths problem 

hyperSpec/codecov.yml
Addresses #194. See also #205.
=> Address codecov paths problem (Take 2)

hyperSpec/R/spc.bin.R
=> Fix $spc colnames in spc.bin()

hyperSpec/NEWS.md, hyperSpec/R/spc.NA.approx.R, hyperSpec/vignettes/hyperSpec.Rmd
=> Remove spc.NA.linapprox()

hyperSpec/NEWS.md, hyperSpec/R/spc.loess.R
=> Fix/245 and improve spc.loess()

.github/workflows/R-CMD-check.yaml, .github/workflows/test-coverage.yaml
=> Update GH Actions setup for code coverage

hyperSpec/inst/schemes/r-hyperspec-family.gv
I add this scheme in order it won't get lost.
=> Add scheme with relationship between r-hyperspec packages

hyperSpec/DESCRIPTION
=> Update version number to v0.100.0

hyperSpec/DESCRIPTION
To avoid package dependency errors like this one:
=> Revert version number

.github/workflows/build_check_deploy.yaml, hyperSpec/DESCRIPTION, hyperSpec/inst/schemes/r-hyperspec-family.gv
Rename
hySpc.pkgs → pkg-repo
hySpc-pkgs → tmp-pkg-repo-dir
=> Update for renamed hySpc.pkgs → pkg-repo

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml
`R-CMD-check` and `pkgdown` GHA workflows were updated in accordance with the recent updates in https://github.com/r-lib/actions/tree/master/examples
=> Update GHA workflows

hyperSpec/vignettes/baseline.Rmd, hyperSpec/vignettes/fileio.Rmd, hyperSpec/vignettes/flu.Rmd, hyperSpec/vignettes/hyperSpec.Rmd, hyperSpec/vignettes/laser.Rmd
=> Use title-case in headers of vignettes

.github/workflows/R-CMD-check.yaml
=> Use R 'release' instead of '4.0.3' on Linux again

.github/workflows/R-CMD-check.yaml
=> Update R CMD check on GHA
